/*
Copyright CHORA INFORMATIQUE 2010-2011
 */

package com.choranet.badr.core.model.commande;

/**
 * @Description liste des commandes supportees par l application
 * @version 1.0-SNAPSHOT
 * @date 20 févr. 2011
 * @author rabbah
 */
public enum BriquesTechniquesCommandes {

    ZK, FLEX, OPENLASZLO, EXPORT, JASPER, DYNAMICJASPERREPORT,
    SEARCHABLE, WEBSEARCH, ACEGI, JSECURITY, SPRINGSECURITYCORE, ENCRYPTION,
    LDAP, WSCLIENT, RESTCLIENT, CXF, SPRINGWS, APACHEAXIS2, ACTIVITIBPM,
    AJAXFLOW, GRAILSFLOW, OSWORKFLOW, JMS, ACTIVEMQ, JMX, DYNAMICDOMAINCLASS,
    DBUTIL, WEBTEST, FUNCTIONALTESTING, SELENIUM, FITENESSE, DBUNIT,
    AUDITTRAIL, AUDITLOGGIN, CLASSDIAGRAM, CREATEDOMAINUML, LICENSE, QUARTZ,
    REVERSEENGENIEERING, APPLICATIONINFO, CLAMAV, OSGI, MAIL, YUI, APPLET,
    RICHUI, FILEUPLOADER, SIMPLECAPTCHA, FORMHELPER, FCKEDITOR, GOOGLECHART,
    OPENFLASHCHART, JFREECHART, WEBSNAPS, IMAGEZOOM, CSVPARSER, EXCELIMPORT, I18
}
